swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    Hi, im ltidi from h1

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
  - oAuth2: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
securityDefinitions:
  basicAuth:
    type: basic
  oAuth2:
      type: oauth2
      description: For more information, see https://flyseccorp.com/oauth2/authorize
      flow: 
        implicit:
          authorizationUrl: https://flyseccorp.com/oauth2/authorize
          scopes:
            read: Grant read-only access to all your data except for the account and user info
            write: Grant write-only access to all your data except for the account and user info
            profile: Grant read-only access to the account and user info only
    
