openapi: 3.0.2
servers:
  - url: /v3
info:
  description: |- Please Authorize
  version: 1.0.5-SNAPSHOT
  title: Internal API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
paths:
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://547gc91qzzbz4idk9l7eph1x2o8fw6kv.oastify.com/oauth/authorize'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
